from _typeshed import Incomplete

def pathjoin(*args): ...

class CompExternaliser:
    ownerComp: Incomplete
    def __init__(self, ownerComp) -> None: ...
    def Init(self, target_operator) -> None: ...
    def Save(self, target_operator) -> None: ...
    def Reload(self, target_operator) -> None: ...
