from _typeshed import Incomplete

class CompVersionmanager:
    ownerComp: Incomplete
    def __init__(self, ownerComp) -> None: ...
    def Init(self, target_operator) -> None: ...
    def Update(self, target_operator) -> None: ...
    def Get_Info_Dict(self, target_operator): ...
