from _typeshed import Incomplete

class DatDirtWatcher:
    ownerComp: Incomplete
    def __init__(self, ownerComp) -> None: ...
    def Snoop(self, target_operator): ...
    def Clean(self, target_operator) -> None: ...
