from _typeshed import Incomplete
from typing import Union

Suspect = Union[DAT, COMP]

class PrivateInvestigator:
    ownerComp: Incomplete
    def __init__(self, ownerComp) -> None: ...
    def possible_suspects(self, op_type: str): ...
    def ReinitSuspects(self) -> None: ...
    def Scan(self) -> None: ...
    def Update(self) -> None: ...
    @property
    def State(self): ...
    def Add(self, operator: Suspect): ...
    def Save(self, operator: COMP): ...
    def Release(self, operator: COMP): ...
    def Get_Dirt(self, operator: Suspect): ...
    def Get_Info(self, operator: Suspect): ...
    def Edit(self, operator: Suspect): ...
    def View(self, operator: Suspect): ...
    def Reload(self, operator: Suspect): ...
